# Generated by Django 5.1.2 on 2024-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankuser",
            name="citizen_num",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
