# Generated by Django 5.1.2 on 2024-11-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("transfer", "Transfer"),
                            ("payment", "Payment"),
                            ("withdraw", "Withdraw"),
                            ("deposit", "Deposit"),
                            ("loan", "Loan"),
                            ("credit", "Credit"),
                            ("credit_usage", "Pay With Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sender_new_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reciever_new_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reciever_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "sender_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
