# Generated by Django 5.1.2 on 2024-11-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_taken", models.DateField(null=True)),
                ("date_finished", models.DateField(null=True)),
                ("amount", models.IntegerField()),
                ("payments", models.IntegerField()),
                ("loan_number", models.IntegerField(blank=True, null=True)),
                ("left_to_pay", models.IntegerField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
